version: '3.3'

services: 
    buscacep:
        build: .
        restart: always
        ports: 

            - 8080:80
        volumes:
#            - ./www:/var/www/html/
#            - ./nginx-sites-available:/etc/nginx/sites-available/
#            - ./www:/usr/share/nginx/html/
            - ./cep:/usr/share/nginx/html/buscacep/
            - ./cep:/usr/share/nginx/html/