version: '3.3'

services: 
    buscacep:
        build: .
        restart: always
        ports: 

            - 8080:80
        volumes:
            - ./cep:/usr/share/nginx/html/buscacep/
            - ./cep:/usr/share/nginx/html/